wI2L/fizz

README.md
fizz.go
fizz_test.go
openapi/operation.go
testdata/spec.json
testdata/spec.yaml

InputModel overrides the binding model of an operation, allowing usage of generic handlers.
```go
type testInputModel struct {
PathParam1 string `path:"a"`
PathParam2 int    `path:"b"`
QueryParam string `query:"q"`
}
fizz.GET("/test/:a/:b", []OperationOption{
ID("GetTest2"),
InputModel(&testInputModel{}),
},
tonic.Handler(func(c *gin.Context) error {
return nil
}, 200)
)
```

Add InputModel OperationOption

---

fizz_test.go
openapi/generator.go
openapi/generator_test.go
testdata/spec.json
testdata/spec.yaml

This will allow configuring custom servers for OpenAPI Specs

Add SetServers to manually configure spec servers

---

README.md
openapi/generator.go
openapi/spec.go
testdata/schemas/path-item.json

depends on https://github.com/loopfz/gadgeto/pull/58

generator: handle Style/Explode values for Query parameters.

---

fizz.go
fizz_test.go

There is currently an issue when using a router group and a tonic handler together. The path is consolidated for the openapi spec operation (but only in case there is a tonic handler), but overrides the path which is later used to declare the route on the underlying gin router.
For example:
```go
r := fizz.New()
g := r.Group("/test", "test", "test group")
g.GET("", tonic.Handler(func (c *gin.Context, in *Input) error {
...
}))
```
This example will declare a route in gin as `/test/test` instead of just `/test`.

Copy consolidated path for openapi spec

---

.gitignore
README.md
examples/market/market.go
openapi/generator.go
openapi/generator_test.go
openapi/spec.go

Fixes #32 
This PR introduces the support for example tags on structs that can be used to generate examples in Open API.

Support example tag on structs

---

README.md
examples/market/router.go
fizz.go
fizz_test.go
openapi/generator.go
openapi/generator_test.go
openapi/operation.go
testdata/spec.json
testdata/spec.yaml

It's me again with proposed changes for handling examples 🙈 
_**NOTICE:** This PR is far from being done, but I just wanted to reach out and check if this is something we want to put in eventually before I spend more time polishing it. Let me know what you think._
With these changes, we could provide one or more examples with the newly proposed `OperationOption`s. The core of the idea is that, even if the response structs for some endpoints (or responses) are the same, we might want to show different examples.
For example in my codebase, we use the `Error` struct (see below) as a generic struct for returning all the server errors. And while the same struct is used on responses with codes `400`, `404`, and `500`, we would like examples to differ; which is not possible with the newly …

Add example to fizz.Response & add fizz.ResponseWithExamples

---

fizz_test.go
openapi/generator.go
openapi/types.go
testdata/spec.json
testdata/spec.yaml

Closes https://github.com/wI2L/fizz/issues/51
Added handling for empty `interface{}` so that it's represented like an "any" type in OpenAPI.
From the specs: https://swagger.io/docs/specification/data-models/data-types/#any
> **Any Type**
> A schema without a type matches any data type – numbers, strings, objects, and so on. `{}` is shorthand syntax for an arbitrary-type schema:
> ```yaml
> components:
>   schemas:
>     AnyValue: {}
> ```
> If you want to provide a description:
> ```yaml
> components:
>   schemas:
>     AnyValue:
>       description: Can be any value - string, number, boolean, array or object.
> ```
> The above is equivalent to:
> ```yaml
> components:
>   schemas:
>     AnyValue:
>       anyOf:
>         - type: string
>         - type: number
>         - type: integer
> …
```

Add Any type for empty interface{} objects

---

.gitignore
README.md
fizz.go
fizz_test.go
openapi/generator.go
openapi/operation.go
openapi/spec.go
testdata/spec.json
testdata/spec.yaml

Fixes [Issue #35](https://github.com/wI2L/fizz/issues/35#issue-492088752), continues stale PR #50.
I tried to keep the comments from #50 relevant by resolving conflicts by back-merging and addressing them here. We can squash commits at your discretion.
- adds generator methods
- some edge case test coverage
- marshalling empty `security` field in path section (see [security](https://swagger.io/specification/#oauth-flows-object) parameter - an empty array is used to signal "no security" override)
The last point is the only one that is troublesome since it does not align with the way JSON gets serialised and would benefit from something like [this request](https://github.com/golang/go/issues/22480). The proposed way is backwards compatible but does repeat some code.

Add OpenAPI security (rebase)

---

README.md
fizz.go
fizz_test.go
openapi/generator.go
openapi/operation.go
openapi/spec.go
testdata/spec.json
testdata/spec.yaml

This PR adds the support for marking the endpoints as `x-internal`, which is a mechanism for hiding endpoints in the rendered docs.
Some docs rendering tools (e.g. [ReDoc](https://redoc.ly/docs/cli/guides/hide-apis/#1-marking-paths-and-operations-with-x-internal-true) and [Elements](https://github.com/stoplightio/elements/blob/main/docs/getting-started/usage/web-component.md#configuration)) support the functionality of the endpoints to be hidden from the docs, if they are marked as `x-internal`. The changes here add the support for `x-internal`.

Add x-internal

---

openapi/spec.go

This PR fixes the issue found in the latest [v0.18.0](https://github.com/wI2L/fizz/releases/tag/v0.18.0) release.
`x-tagGroups` which was added in #55 seem to be missing in the latest release. I think the issue happened in the rebasing of the security PR (#59).

Readd x-tagGroups

---

openapi/spec.go

This PR fixes the issue found in the latest [v0.18.0](https://github.com/wI2L/fizz/releases/tag/v0.18.0) release.
`x-internal` is never exposed any more. I think the issue is in the `omitOperationNilFields` where we did not copy the value of `x-internal` over.

fix: omission of x-internal operation field

---

README.md

I got confused why there is no OpenAPI static method and then realized that it's a struct method

docs: clarify scope of OpenAPI method

---

README.md
fizz_test.go
openapi/generator.go
openapi/generator_test.go
openapi/types.go
testdata/spec.json
testdata/spec.yaml

Support providing examples for custom types

---

fizz_test.go
openapi/generator.go
openapi/spec.go
testdata/spec.json
testdata/spec.yaml

fix: Security as array and valid spec in tests

---

README.md
openapi/generator.go
openapi/spec.go

Security mecanisms need to be declared at the top level of the
specification, in order to be used on operations. SetSecuritySchemes
allow user to personalize securitySchemes of the specification.

feat(spec): add SetSecuritySchemes to declare the securitySchemes in the specification

---

openapi/generator.go
openapi/generator_test.go

This commit set the schema format to "email" if the email validator is
set on a field.

Configure the schema format if the email validator is set

---

README.md
openapi/spec.go

Changes:
- `exanple` -> `example` in openapi/spec.go
- `minIntem` -> `minItem` in README.md

docs: fix typo

---

openapi/spec.go

The field is required by the spec, and may be empty.
closes #86

fix(spec): marshal OAuthFlow's scopes as an empty map if nil

---

openapi/generator.go
openapi/generator_test.go
testdata/schemas/X.json

If we would take for example a kube object [Pod](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3939) it has `ObjectMeta` as an embedded field but if we render it via `json.Marshal` we would get a nice `metadata` field in our json.
However in our OpenAPI definition this field would be missing.

Use tag to determine if to flatten or not an embedded anonymous field

---

openapi/generator.go
openapi/generator_test.go

Defining an optional (pointer) enum field results in an error:
```
type Param struct {
EnumParam *string `query:"enumParam" enum:"a,b" example:"a" default:"a" description:"Enum parameter"`
}
```
`enum value a cannot be converted to field type: unknown type *string: field=enumParam, type=`
Since nullable enum fields are viable, this PR adds support for them

Nullable enum fields
